import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { api } from '../services/api';

const types = [{ key: 'departments', label: 'Departments' }, { key: 'designations', label: 'Designations' }, { key: 'tracks', label: 'Role specializations' }, { key: 'technologies', label: 'Technologies & skills' }];
export default function Catalogs() {
  const [tab, setTab] = useState(0); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const type = types[tab].key; const client = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ['catalog', type], queryFn: () => api.get(`/catalog/${type}`, { params: { limit: 500 } }).then((response) => response.data.data) });
  const mutation = useMutation({ mutationFn: () => api.post(`/catalog/${type}`, { name }), onSuccess: () => { client.invalidateQueries({ queryKey: ['catalog', type] }); setName(''); setOpen(false); } });
  return <Stack spacing={3}><Box><Typography variant="h4">Company structure</Typography><Typography color="text.secondary" sx={{ mt: .7 }}>Departments, job titles, specializations (UI/UX, Python, AI/ML, Frontend), and skills used across recruitment and employees.</Typography></Box><Card><Tabs value={tab} onChange={(_event, value) => setTab(value)} variant="scrollable">{types.map((item) => <Tab key={item.key} label={item.label} />)}</Tabs><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}><Typography variant="h6">{types[tab].label}</Typography><Button variant="contained" onClick={() => setOpen(true)}>+ Add</Button></Stack>{isLoading ? <Typography color="text.secondary">Loading…</Typography> : <Stack direction="row" gap={1} flexWrap="wrap">{data?.map((item) => <Chip key={item._id} label={item.name} />)}{!data?.length && <Typography color="text.secondary">No entries yet.</Typography>}</Stack>}</CardContent></Card><Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Add {types[tab].label.slice(0, -1)}</DialogTitle><DialogContent><TextField autoFocus fullWidth label="Name" value={name} onChange={(event) => setName(event.target.value)} sx={{ mt: 1 }} />{mutation.isError && <Alert severity="error" sx={{ mt: 2 }}>Could not create this entry.</Alert>}</DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" disabled={!name.trim() || mutation.isPending} onClick={() => mutation.mutate()}>Save</Button></DialogActions></Dialog></Stack>;
}
