import React, { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Alert, Autocomplete, Box, Button, Card, CardContent, Chip, Stack, TextField, Typography } from '@mui/material';
import { api } from '../services/api';

export default function Email() {
  const [to, setTo] = useState([]); const [cc, setCc] = useState([]); const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [files, setFiles] = useState([]);
  const recipients = useQuery({ queryKey: ['email-recipients'], queryFn: () => api.get('/email/recipients').then((response) => response.data.data) });
  const send = useMutation({ mutationFn: () => { const form = new FormData(); form.append('to', to.join(',')); form.append('cc', cc.join(',')); form.append('subject', subject); form.append('body', body); files.forEach((file) => form.append('attachments', file)); return api.post('/email/send', form); }, onSuccess: () => { setTo([]); setCc([]); setSubject(''); setBody(''); setFiles([]); } });
  const options = recipients.data || [];
  const submit = (event) => { event.preventDefault(); send.mutate(); };
  return <Stack spacing={3}><Box><Typography variant="h4">Email</Typography><Typography color="text.secondary" sx={{ mt: .7 }}>Send secure messages to employees and CRM users through your Zoho Mail account.</Typography></Box><Card><CardContent component="form" onSubmit={submit}><Stack spacing={2.5}><Autocomplete multiple freeSolo options={options.map((recipient) => recipient.email)} value={to} onChange={(_event, value) => setTo(value)} renderTags={(values, getTagProps) => values.map((value, index) => <Chip label={value} {...getTagProps({ index })} key={value} />)} renderInput={(params) => <TextField {...params} label="To" placeholder="Add email addresses" required helperText="Type an email and press Enter. Separate recipients are sent individually." />} /><Autocomplete multiple freeSolo options={options.map((recipient) => recipient.email)} value={cc} onChange={(_event, value) => setCc(value)} renderTags={(values, getTagProps) => values.map((value, index) => <Chip label={value} {...getTagProps({ index })} key={value} />)} renderInput={(params) => <TextField {...params} label="CC" placeholder="Optional CC recipients" />} /><TextField label="Subject" value={subject} onChange={(event) => setSubject(event.target.value)} required fullWidth /><TextField label="Message" value={body} onChange={(event) => setBody(event.target.value)} required fullWidth multiline minRows={10} placeholder="Write your message…" /><Box><Button component="label" variant="outlined">+ Add PDF or image<input hidden type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.gif,.webp" onChange={(event) => setFiles(Array.from(event.target.files || []))} /></Button>{files.length > 0 && <Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 1 }}>{files.map((file) => <Chip key={file.name} label={file.name} onDelete={() => setFiles((current) => current.filter((item) => item !== file))} />)}</Stack>}</Box>{send.isError && <Alert severity="error">{send.error.response?.data?.message || 'Email could not be sent.'}</Alert>}{send.isSuccess && <Alert severity="success">Email sent successfully.</Alert>}<Button type="submit" variant="contained" size="large" disabled={send.isPending || !to.length || !subject.trim() || !body.trim()}>{send.isPending ? 'Sending…' : 'Send email'}</Button></Stack></CardContent></Card></Stack>;
}
